name: Deploy package to GitHub package registry
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup actions"
        uses: actions/checkout@v1
      - name: "npm/registry setup"
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
          scope: "@OWNER"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_Token }}
      - name: "publish package"
        run: |
          npm run test 
          npm run build
          echo @OWNER:registry=https://npm.pkg.github.com/ >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_Token }}
